import "./globals.css";
import NavBar from "../components/other/navbar"
import { Chillax_Semibold } from "./fonts";





export const metadata = {
    title: "Hope",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html className={Chillax_Semibold} lang="en">
            <body>
              <div>
                {children}
              </div>
            </body>
        </html>
    );
}
